SELECT 
    B.AUTHOR_ID,	
    AUTHOR_NAME,	
    CATEGORY,
    SUM(SALES*PRICE) AS TOTAL_SALES
FROM 
    BOOK AS B
JOIN 
    AUTHOR AS A
ON 
    B.AUTHOR_ID = A.AUTHOR_ID
JOIN 
    BOOK_SALEs AS BS
ON 
    B.BOOK_ID = BS.BOOK_ID
WHERE 
    Bs.SALES_DATE >= "2022-01-01" AND BS.SALES_DATE <= "2022-01-31"
GROUP BY
    B.AUTHOR_ID,	
    AUTHOR_NAME,	
    CATEGORY
ORDER BY 
    B.AUTHOR_ID,
    CATEGORY DESC