-- 코드를 입력하세요
SELECT
    PRODUCT_CODE,
    SUM(PR.PRICE * OS.SALES_AMOUNT) AS SALES
FROM
    OFFLINE_SALE AS OS
JOIN
    PRODUCT AS PR
ON OS.PRODUCT_ID = PR.PRODUCT_ID 
GROUP BY
    PRODUCT_CODE
ORDER BY
    SALES DESC,
    PRODUCT_CODE

    
