-- 코드를 입력하세요
SELECT 
    DATE_FORMAT(COMBINE_DATA.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    COMBINE_DATA.PRODUCT_ID,
    COMBINE_DATA.USER_ID,
    COMBINE_DATA.SALES_AMOUNT
FROM (
    SELECT 
        SALES_DATE,
        PRODUCT_ID,
        USER_ID,
        SALES_AMOUNT
    FROM ONLINE_SALE
    UNION ALL
    SELECT 
        SALES_DATE,
        PRODUCT_ID,
        NULL AS USER_ID,
        SALES_AMOUNT
    FROM OFFLINE_SALE 
) AS COMBINE_DATA
WHERE COMBINE_DATA.SALES_DATE between "2022-03-01" AND "2022-03-31"
ORDER BY COMBINE_DATA.SALES_DATE, COMBINE_DATA.PRODUCT_ID, COMBINE_DATA.USER_ID