-- 코드를 작성해주세요

SELECT ROUTE,concat(round(SUM(D_BETWEEN_DIST),1),"km") AS TOTAL_DISTANCE, concat(round(avg(D_BETWEEN_DIST),2),"km")
AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE 
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC