-- 코드를 입력하세요
WITH user2021 AS (
        SELECT USER_ID
        FROM USER_INFO
        WHERE JOINED LIKE "2021%")

SELECT
    YEAR(OS.SALES_DATE) AS YEAR,
    MONTH(OS.SALES_DATE) AS MONTH,
    COUNT(DISTINCT(USER_ID)) AS PUCHASED_RATIO,
    ROUND(COUNT(DISTINCT(USER_ID)) / (SELECT COUNT(USER_ID) FROM user2021), 1) AS PUCHASED_RATIO

FROM 
    ONLINE_SALE AS OS
WHERE
    OS.USER_ID IN (SELECT USER_ID FROM user2021)
GROUP BY
    YEAR,MONTH
ORDER BY 
    YEAR,MONTH
    
