-- 코드를 작성해주세요


select 
    CONCAT(QUARTER(DIFFERENTIATION_DATE),"Q") as QUARTER
    , COUNT(*) as ECOLI_COUNT
from
    ECOLI_DATA
GROUP BY
    CONCAT(QUARTER(DIFFERENTIATION_DATE),"Q")
ORDER BY
    QUARTER