-- 코드를 입력하세요
SELECT
    FD.PRODUCT_ID,
    FD.PRODUCT_NAME,
    SUM(FD.PRICE*FO.AMOUNT) AS TOTAL_SALES
FROM
    FOOD_ORDER AS FO
JOIN 
    FOOD_PRODUCT AS FD
ON
    FD.PRODUCT_ID = FO.PRODUCT_ID
WHERE 
    PRODUCE_DATE LIKE "2022-05%"
GROUP BY
    PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    PRODUCT_ID ASC
    
    