-- 코드를 입력하세요
WITH SALE_TABLE AS (
    SELECT 
        CAR_TYPE, cast(replace(DURATION_TYPE,"일 이상","")as UNSIGNED) as DURATION, DISCOUNT_RATE
    FROM 
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN  
    WHERE 
        CAR_TYPE = "트럭"
    ORDER BY CAR_TYPE, DURATION
),
CAR_DAY_HISTORY AS (   
    SELECT 
       HISTORY_ID,CAR_TYPE, (DATEDIFF(END_DATE,START_DATE) + 1) * DAILY_FEE AS PRICE, DATEDIFF(END_DATE,START_DATE) + 1 AS DURATION
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
    JOIN
        CAR_RENTAL_COMPANY_CAR CC
    WHERE 
        CH.CAR_ID = CC.CAR_ID AND
        CC.CAR_TYPE = "트럭"  
)

# select * FROM CAR_DAY_HISTORY
# order by HISTORY_ID
select HISTORY_ID, MIN(CAST(CH.PRICE * (1 - IFNULL(ST.DISCOUNT_RATE,0) / 100) AS UNSIGNED)) AS FEE
FROM CAR_DAY_HISTORY CH
LEFT JOIN SALE_TABLE ST
ON CH.CAR_TYPE = ST.CAR_TYPE AND  CH.DURATION >= ST.DURATION

GROUP BY 
    HISTORY_ID
ORDER BY
    FEE DESC,
    HISTORY_ID DESC
    

    
-- 대여 기록 ID와 대여 금액 리스트를 출력


-- 자동차 종류가   '트럭'
-- 자동차의 대여 기록에 대해서 대여 기록 별 대여 금액(컬럼명: FEE)