SELECT ITEM_INFO.ITEM_ID,ITEM_INFO.ITEM_NAME,ITEM_INFO.RARITY
FROM (
    SELECT ITEM_TREE.ITEM_ID
    FROM ITEM_TREE JOIN ITEM_INFO
    ON ITEM_TREE.PARENT_ITEM_ID = ITEM_INFO.ITEM_ID
    WHERE ITEM_INFO.RARITY = "RARE"
    ) 
    AS RARE_ITEM JOIN ITEM_INFO
ON RARE_ITEM.ITEM_ID = ITEM_INFO.ITEM_ID
ORDER BY ITEM_ID DESC