-- 코드를 입력하세요
SELECT 
    MONTH(CH.start_date) AS MONTH,
    CH.CAR_ID,
    COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
WHERE CH.START_DATE >= "2022-08-01" AND CH.START_DATE < "2022-11-01"
    AND CH.CAR_ID IN
    (SELECT 
        CAR_ID
    frOM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE >= "2022-08-01" AND START_DATE < "2022-11-01"
    GROUP BY
        CAR_ID
    HAVING 
        count(*) >= 5
    )
GROUP BY
    MONTH,
    CH.CAR_ID
ORDER BY
    MONTH,
    CAR_ID DESC