-- 코드를 작성해주세요

SELECT
    SUM(SCORE) as SCORE
    , HR_EMPLOYEES.EMP_NO
    , HR_EMPLOYEES.EMP_NAME
    , POSITION
    , EMAIL
FROM
    HR_EMPLOYEES 
JOIN HR_GRADE ON HR_EMPLOYEES.EMP_NO = HR_GRADE.EMP_NO
WHERE 
    HR_GRADE.YEAR = 2022
GROUP BY
    HR_EMPLOYEES.EMP_NO
ORDER BY
    SUM(SCORE) DESC
LIMIT 1