-- 코드를 입력하세요
SELECT 
    BOOK.CATEGORY,
    SUM(SALES) AS SALES
FROM BOOK_SALES JOIN BOOK
ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
WHERE SALES_DATE LIKE "2022-01%"
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY